import { getConfig, saveConfig } from '../components/config.js'

const schemas = [
  {
    field: 'schedule.enabled',
    label: '启用定时续火',
    bottomHelpMessage: '关闭后不会按计划自动执行，仍可手动发送 #抖音续火。保存后立即生效。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'schedule.cron',
    label: 'Cron 表达式',
    bottomHelpMessage: '使用 6 段（秒 分 时 日 月 周），例如每天 08:10：0 10 8 * * *。保存后会自动重新安排定时任务。',
    component: 'EasyCron',
    required: false,
    componentProps: { placeholder: '0 10 8 * * *' },
  },
  {
    field: 'browser.preferSystem',
    label: '优先复用系统浏览器',
    bottomHelpMessage: '浏览器仅用于扫码登录获取 Cookie（发送消息走 API）。开启后自动探测本机已安装的 Edge、Chrome 或 Chromium 并直接使用，无需下载 Playwright 自带 Chromium；探测不到时回落到自带 Chromium。下方渠道和路径填写后优先生效。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'browser.channel',
    label: '浏览器渠道',
    bottomHelpMessage: '选择 Edge 或 Chrome 时由 Playwright 自动定位系统已安装的浏览器，无需填写路径；留空则按上方开关自动探测。',
    component: 'Select',
    componentProps: {
      options: [
        { label: '不指定（自动探测或使用自带 Chromium）', value: '' },
        { label: '系统 Edge', value: 'msedge' },
        { label: '系统 Chrome', value: 'chrome' },
      ],
    },
  },
  {
    field: 'browser.executablePath',
    label: '浏览器路径',
    bottomHelpMessage: '手动指定本机 Chrome 或 Edge 的可执行文件路径，填写后优先于上方浏览器渠道；一般留空即可。',
    component: 'Input',
    placeholder: '留空则按浏览器渠道自动定位',
  },
  {
    field: 'browser.headless',
    label: '无头模式',
    bottomHelpMessage: '开启后浏览器在后台运行，不显示窗口；排查页面问题时可关闭。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'message.includeSource',
    label: '一言附带出处',
    bottomHelpMessage: '未设置账号专属消息模板时，是否在随机一言后附带出处。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'message.template',
    label: '默认消息模板',
    bottomHelpMessage: '留空则发送随机一言。可用占位符：{{account}} 账号别名、{{friend}} 会话名、{{yiyan}} 一言正文、{{from}} 一言出处、{{date}} 日期、{{time}} 时间、{{weekday}} 星期；换行写 \\n。账号未填写专属模板时使用这份模板。',
    component: 'Textarea',
    rows: 3,
    defaultValue: '{{friend}}，今天的火花到账啦🔥\\n{{yiyan}}\\n——「{{from}}」\\n{{date}} {{weekday}}',
    placeholder: '{{friend}}，今天的火花到账啦🔥\\n{{yiyan}}\\n——「{{from}}」\\n{{date}} {{weekday}}',
  },
  { component: 'Divider', label: '私信发送' },
  {
    field: 'send.minIntervalSec',
    label: '发送间隔下限（秒）',
    bottomHelpMessage: '同一账号相邻两个续火目标之间的随机延时下限，降低抖音风控概率。',
    component: 'InputNumber',
    min: 0,
    max: 600,
    defaultValue: 3,
  },
  {
    field: 'send.maxIntervalSec',
    label: '发送间隔上限（秒）',
    bottomHelpMessage: '同一账号相邻两个续火目标之间的随机延时上限。',
    component: 'InputNumber',
    min: 1,
    max: 600,
    defaultValue: 8,
  },
  {
    field: 'send.skipIfSentToday',
    label: '跳过今天已续火的会话',
    bottomHelpMessage: '开启后，续火前会检查会话最近消息，今天已经给对方发过的直接跳过（火花每天只需发一次，重复发无意义）。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'im.templateB64',
    label: '自定义 IM 请求模板',
    bottomHelpMessage: '一般留空。内置私信请求模板失效时，浏览器 F12 抓取一次真实 message/send 请求体（protobuf 二进制）转 Base64 后粘贴到这里。',
    component: 'Textarea',
    rows: 2,
    placeholder: '留空使用内置模板',
  },
  {
    field: 'im.profileFetchLimit',
    label: '昵称补全人数上限',
    bottomHelpMessage: '拉取会话列表时最多为多少人查询昵称和抖音号；超出的人会显示在列表中但没有昵称。调小可加快拉取速度。',
    component: 'InputNumber',
    min: 1,
    max: 200,
    defaultValue: 30,
  },
  { component: 'Divider', label: '网页账号配置' },
  {
    field: 'web.mountToTrss',
    label: '挂载到 TRSS 网页服务',
    bottomHelpMessage: '开启时页面路径为 /douyin-id-spark；关闭后插件使用独立端口。添加账号可在群聊或私聊使用，修改账号必须私聊。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'web.standalonePort',
    label: '独立网页端口',
    bottomHelpMessage: '仅在未挂载到 TRSS 时使用。端口需未被其他程序占用；修改端口后需重启云崽。',
    component: 'InputNumber',
    min: 1,
    max: 65535,
    defaultValue: 3066,
  },
  {
    field: 'web.baseUrl',
    label: '网页访问地址',
    bottomHelpMessage: '机器人发出的链接以此地址开头，填写你点链接的那台设备能访问到的完整地址，端口要和实际服务端口一致，例如 http://192.168.1.10:2536。末尾斜杠可省略，但必须带 http:// 或 https://。留空时挂载模式取云崽的 Bot.url，独立模式取 http://127.0.0.1:独立端口（手机访问不到）。',
    component: 'Input',
    placeholder: 'http://192.168.1.10:2536',
  },
  {
    field: 'web.linkExpiresMinutes',
    label: '链接有效分钟数',
    bottomHelpMessage: '添加或修改账号时生成的网页链接有效时长，过期后需要重新向机器人发送命令。',
    component: 'InputNumber',
    min: 1,
    max: 60,
    defaultValue: 10,
  },
  {
    field: 'web.recallSetupMessageOnComplete',
    label: '账号保存后撤回链接',
    bottomHelpMessage: '账号添加或修改成功后撤回机器人发送的网页链接消息；关闭则保留链接直到过期。',
    component: 'Switch',
    defaultValue: false,
  },
  {
    field: 'web.setupMessageRecallSeconds',
    label: '网页链接自动撤回秒数',
    bottomHelpMessage: '网页链接发送后自动撤回的时间，0 表示不自动撤回；与“账号保存后撤回链接”可同时开启。',
    component: 'InputNumber',
    min: 0,
    max: 86400,
    defaultValue: 0,
  },
  { component: 'Divider', label: 'SMTP 邮件通知' },
  {
    field: 'smtp.enabled',
    label: '启用邮件通知',
    bottomHelpMessage: '开启后可向用户发送续火失败邮件；用户开启成功通知时也会使用此邮件配置。',
    component: 'Switch',
    defaultValue: false,
  },
  {
    field: 'smtp.host',
    label: 'SMTP 主机',
    bottomHelpMessage: '邮件服务商的 SMTP 服务器地址，例如 QQ 邮箱为 smtp.qq.com。',
    component: 'Input',
  },
  {
    field: 'smtp.port',
    label: 'SMTP 端口',
    bottomHelpMessage: '常用 SSL 端口为 465；非 SSL 服务通常使用 25、587 等端口。',
    component: 'InputNumber',
    min: 1,
    max: 65535,
    defaultValue: 465,
  },
  {
    field: 'smtp.secure',
    label: '启用 SSL',
    bottomHelpMessage: '端口为 465 时通常需要开启；请以邮件服务商的说明为准。',
    component: 'Switch',
    defaultValue: true,
  },
  {
    field: 'smtp.username',
    label: 'SMTP 用户名',
    bottomHelpMessage: '用于登录 SMTP 服务，通常填写完整邮箱地址。',
    component: 'Input',
  },
  {
    field: 'smtp.password',
    label: 'SMTP 授权码',
    bottomHelpMessage: '填写邮件服务商生成的 SMTP 授权码，不是邮箱登录密码。',
    component: 'Input',
  },
  {
    field: 'smtp.from',
    label: '发件人',
    bottomHelpMessage: '邮件中显示的发件人地址；留空时使用 SMTP 用户名。',
    component: 'Input',
  },
]

export default {
  schemas,
  getConfigData: () => getConfig(),
  setConfigData(data, { Result }) {
    saveConfig(data)
    return Result.ok({}, '保存成功')
  },
}
